name: CI

on: [push]
jobs:
  Run_workspace_Tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2

    # Select Xcode 15.2 explicitly
    - name: Select Xcode 15.2
      run: sudo xcode-select --switch /Applications/Xcode_15.2.app && xcodebuild -version

    # Run unit tests
    - name: Run unit tests
      run: xcodebuild test -scheme Blocks -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2'
